ALTER TABLE `Catalog` ADD COLUMN `hasPassword` BOOLEAN NOT NULL DEFAULT false, ADD COLUMN `password` VARCHAR(191) NULL, ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'active', ADD COLUMN `views` INTEGER NOT NULL DEFAULT 0;

ALTER TABLE `Customer` ADD COLUMN `lastLogin` DATETIME(3) NULL, ADD COLUMN `region` VARCHAR(191) NULL, ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'active', ADD COLUMN `joinedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `Inquiry` ADD COLUMN `priority` VARCHAR(191) NOT NULL DEFAULT 'medium', ADD COLUMN `productName` VARCHAR(191) NULL;

ALTER TABLE `Product` MODIFY `description` VARCHAR(191) NULL, ADD COLUMN `shortDescription` VARCHAR(100) NULL;
